package org.devabir.common;

import org.lwjgl.BufferUtils;
import org.lwjgl.system.MemoryUtil;

import java.nio.ByteBuffer;
import java.nio.FloatBuffer;
import java.nio.IntBuffer;

import static org.lwjgl.opengl.GL46.*;

/**
 * Generic OpenGL buffer (VBO, SSBO, UBO, etc.)
 */
public class GLBuffer implements AutoCloseable {
    private final int id;
    private final int target;
    private final int usage;
    private final String name;
    private int elementCount;

    public GLBuffer(String name, int target, int usage) {
        this.name = name;
        this.target = target;
        this.usage = usage;
        this.id = glGenBuffers();
    }

    public void bind() {
        glBindBuffer(target, id);
    }

    public void unbind() {
        glBindBuffer(target, 0);
    }

    /* ---------- Data upload / allocate ---------- */

    // here, the buffer will just be allocated,
    // contents will be generated by the GPU
    public void allocate(long size) {
        bind();
        glBufferData(target, size, usage);
        unbind();
    }

    // Yeah IK generics, but why complicate simple code?
    // TODO: these memAllocFloat and free should be implemented by the caller
    // and use it all throughout the fetch, upload process
    public void upload(float[] data) {
        FloatBuffer buffer = MemoryUtil.memAllocFloat(data.length);
        buffer.put(data).flip();
        this.elementCount = data.length;
        bind();
        glBufferData(target, buffer, usage);
        unbind();
        MemoryUtil.memFree(buffer);
    }

    public void upload(int[] data) {
        IntBuffer buffer = MemoryUtil.memAllocInt(data.length);
        buffer.put(data).flip();
        this.elementCount = data.length;
        bind();
        glBufferData(target, buffer, usage);
        unbind();
        MemoryUtil.memFree(buffer);
    }

    /* ---------- SSBO binding ---------- */

    public void bindBase(int bindingIndex) {
        glBindBufferBase(target, bindingIndex, id);
    }

    /* ---------- Getters ---------- */

    public int getId() {
        return id;
    }

    public int getElementCount() {
        return elementCount;
    }

    public String getName() {
        return name;
    }

    public void dispose() {
        glDeleteBuffers(id);
    }

    @Override
    public void close() throws Exception {
        glDeleteBuffers(this.id);
    }
}
